### ISSUE TITLE
ENOENT: no such file or directory, stat '/usr/bin/hlint'

### ISSUE THREAD

**Issue by fabianhjr** [AtomLinter/linter-hlint#10]
Error: ENOENT: no such file or directory, stat ''/usr/bin/hlint'
      at Error (native)
      at fs.statSync (fs.js:846:18)
      at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
      at LinterHLint.Linter._cachedStatSync (/home/fabianhjr/.atom/packages/linter/lib/linter.coffee:87:17)
      at LinterHLint.Linter.getCmdAndArgs (/home/fabianhjr/.atom/packages/linter/lib/linter.coffee:104:16)
      at LinterHLint.Linter.lintFile (/home/fabianhjr/.atom/packages/linter/lib/linter.coffee:151:24)
      at lintFile (/home/fabianhjr/.atom/packages/linter/lib/legacy.coffee:66:16)
      at /home/fabianhjr/.atom/packages/linter/lib/legacy.coffee:80:11

`hlint` is installed and works; Used `which hlint` to find the path to hlint and I am getting this error.

**Comment by mdgriffith** [comment]
Do you have a leading single quote in the filepath?  The error message has two single quotes at the beginning:  ''/usr/bin/hlint'

**Comment by fabianhjr** [comment]
There were no quotes on the config. Should there be?

(I was messing around changing /usr/bin/hlint to just hlint and messed up on the copy paste.)

This is what I have in the path setting: /usr/bin/hlint.

Though after restarting it seems to have fixed itself. 0_o

Sorry, will try to figure out whats wrong on my side but it was also happening to linter-hdev. Will investigate further and come back if I find anything.

**Comment by mdgriffith** [comment]
OK, cool.  Let me know if you encounter it again.

And, no, there should be no quotes :)
