### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by jplatte** [AtomLinter/linter-hlint#6]
I'm getting this error when invalid Haskell code is on the last line of a file being linted (when a line of invalid Haskell code isn't terminated by `\n`, but by `EOF`), e.g. when I write new code at the end of the file and it's linted before it's complete / syntactically correct:

    Uncaught TypeError: Cannot read property 'start' of null
    /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:26
    
    TypeError: Cannot read property 'start' of null
      at Function.module.exports.Range.fromObject (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:26:31)
      at MarkerManager.module.exports.MarkerManager.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-manager.js:84:36)
      at TextBuffer.module.exports.TextBuffer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:605:27)
      at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1279:41)
      at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1270:59)
      at LinterView.createMarker (/home/jonas/.atom/packages/linter/lib/linter-view.coffee:190:22)
      at LinterView.display (/home/jonas/.atom/packages/linter/lib/linter-view.coffee:227:17)
      at LinterView.processMessage (/home/jonas/.atom/packages/linter/lib/linter-view.coffee:178:8)
      at LinterView.processMessage (/home/jonas/.atom/packages/linter/lib/linter-view.coffee:1:1)
      at /home/jonas/.atom/packages/linter/lib/linter-view.coffee:164:14
      at LinterHLint.processMessage (/home/jonas/.atom/packages/linter-hlint/lib/linter-hlint.coffee:31:5)
      at /home/jonas/.atom/packages/linter/lib/linter.coffee:155:8
      at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
      at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
      at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
      at emitOne (events.js:82:20)
      at Socket.emit (events.js:166:7)
      at Pipe.close (net.js:464:12)

This was already reported on the linter plugin repo ([link](https://github.com/AtomLinter/Linter/issues/300)) because that's where Atom says the error is thrown. This doesn't seem to happen with other linter plugins though.

**Comment by mdgriffith** [comment]
I'm having a hard time reproducing this.  I also noticed that when I save a file in atom, that it automatically inserts a newline character at the end if there isn't one.

What version of Atom are you on?

**Comment by jplatte** [comment]
I'm on Atom 0.196.0. What does this issue have to do with automatic newlines on the end when saving? Do you have the linter plugin set up to only lint on save, not on change?

**Comment by mdgriffith** [comment]
Sorry, originally I had it to lint on save and had forgotten about the lint on change option.

I have tried a few times and haven't been able to reproduce this.  Are you still regularly encountering it?

**Comment by jplatte** [comment]
Yes, I'm still encountering it in the same scenario as before. I created a [screencast](https://youtu.be/YSqal3znMZo) as a demonstration.

In case it's unreadable, I just wrote a new line at the end of the file reading

    test =

**Comment by mdgriffith** [comment]
OK, cool, I was able to reproduce and find out what was going on. Not sure why my previous attempts didn't bring up the error....but oh well.  I've published the patch which should take care of it, can you upgrade linter-hlint to 0.3.4 and let me know how it goes?

It looks like when hlint encounters a parse error on the very last line, without a newline at the end, it
reports a line number that is beyond the file.  This was causing Atom to be unable to highlight anything and error.

**Comment by jplatte** [comment]
I updated and the fix seems to work. Thanks! :)
